[package]
name = "life"
version = "0.4.0"
authors = ["Sébastien Job <sebastien.job@gmail.com>"]
edition = "2018"
description = "A game of life."

[dependencies]
rand = "0.7"
structopt = "0.3"
clap = "2.33"
actix-web = "2.0"
serde = "1.0"
serde_json = "1.0"
