[package]
name = "life"
version = "0.4.0"
authors = ["Sébastien Job <sebastien.job@gmail.com>"]
edition = "2018"
description = "A game of life."

[dependencies]
rand = "0.9"
structopt = "0.3"
clap = "4.5"
axum = { version = "0.8", features = ["json"] }
tokio = { version = "1.45", features = ["rt-multi-thread"] }
serde = "1.0"
serde_json = "1.0"
