name: Continuous Integration

# Run tests and checks on pushes to `master`.

# on: [push, pull_request]
on:
    push:
        branches:
            - "**"
    pull_request:
        branches:
            - "**"

jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Run tests
              run: cargo test --verbose

    check:
        name: Check package
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Run check
              run: cargo check

    syntax:
        name: Check syntax
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Run rustfmt
              run: cargo fmt --all -- --check

    lint:
        name: Check using Clippy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Run Clippy
              run: cargo clippy -- -D warnings
